version: "3.9"
services:
api:
build: .
command: npm run dev
ports: ["8000:8000"]
volumes: [".:/workspace"]
env_file: .env
depends_on: [redis]
worker:
build: .
command: node -e "import('./dist/queue/server.ts')"
env_file: .env
volumes: [".:/workspace"]
depends_on: [redis]
redis:
image: redis:7